package pastchallenges;

import java.util.Arrays;

public class ListeningSongs {
    public int listen(int[] durations1, int[] durations2, int minutes, int T) {
        int cnt = 0;
        int seconds = minutes * 60;
        if ( T > durations1.length || T > durations2.length) return -1;

        Arrays.sort(durations1);
        Arrays.sort(durations2);

        int n = durations1.length;
        int m = durations2.length;

        int myScore = 0;
        for (int i = 0; i < T; i++) {
            myScore += durations1[i] + durations2[i];

        }
        if (myScore > seconds) return -1;

        cnt += 2 * T;
        int i = T, j = T;
        while (i < n && j < m) {

            if (durations1[i] < durations2[j]) {
                if (myScore + durations1[i] > seconds) break;
                myScore += durations1[i];
                i++;
                cnt++;
            } else {
                if (myScore + durations2[j] > seconds) break;
                myScore += durations2[j];
                j++;
                cnt++;
            }
        }
        while (i < n) {
            if (myScore + durations1[i] > seconds) break;
            myScore += durations1[i];
            i++;
            cnt++;
        }
        while (j < m) {
            if (myScore + durations2[j] > seconds) break;
            myScore += durations2[j];
            j++;
            cnt++;
        }
        return cnt;
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit-pf 2.3.0
    private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, int p2, int p3, boolean hasAnswer, int p4) {
        System.out.print("Test " + testNum + ": [" + "{");
        for (int i = 0; p0.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(p0[i]);
        }
        System.out.print("}" + "," + "{");
        for (int i = 0; p1.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print(p1[i]);
        }
        System.out.print("}" + "," + p2 + "," + p3);
        System.out.println("]");
        ListeningSongs obj;
        int answer;
        obj = new ListeningSongs();
        long startTime = System.currentTimeMillis();
        answer = obj.listen(p0, p1, p2, p3);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + p4);
        }
        System.out.println("Your answer:");
        System.out.println("\t" + answer);
        if (hasAnswer) {
            res = answer == p4;
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }

    public static void main(String[] args) {
        boolean all_right;
        boolean disabled;
        boolean tests_disabled;
        all_right = true;
        tests_disabled = false;

        int[] p0;
        int[] p1;
        int p2;
        int p3;
        int p4;

        // ----- test 0 -----
        disabled = false;
        p0 = new int[]{300, 200, 100};
        p1 = new int[]{400, 500, 600};
        p2 = 17;
        p3 = 1;
        p4 = 4;
        all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        // ----- test 1 -----
        disabled = false;
        p0 = new int[]{300, 200, 100};
        p1 = new int[]{400, 500, 600};
        p2 = 10;
        p3 = 1;
        p4 = 2;
        all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        // ----- test 2 -----
        disabled = false;
        p0 = new int[]{60, 60, 60};
        p1 = new int[]{60, 60, 60};
        p2 = 5;
        p3 = 2;
        p4 = 5;
        all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        // ----- test 3 -----
        disabled = false;
        p0 = new int[]{120, 120, 120, 120, 120};
        p1 = new int[]{60, 60, 60, 60, 60, 60};
        p2 = 10;
        p3 = 3;
        p4 = 7;
        all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        // ----- test 4 -----
        disabled = false;
        p0 = new int[]{196, 147, 201, 106, 239, 332, 165, 130, 205, 221, 248, 108, 60};
        p1 = new int[]{280, 164, 206, 95, 81, 383, 96, 255, 260, 244, 60, 313, 101};
        p2 = 60;
        p3 = 3;
        p4 = 22;
        all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        // ----- test 5 -----
        disabled = false;
        p0 = new int[]{100, 200, 300};
        p1 = new int[]{100, 200, 300};
        p2 = 2;
        p3 = 1;
        p4 = -1;
        all_right = (disabled || KawigiEdit_RunTest(5, p0, p1, p2, p3, true, p4)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        // ----- test 6 -----
        disabled = false;
        p0 = new int[]{100, 200, 300, 400, 500, 600};
        p1 = new int[]{100, 200};
        p2 = 1000;
        p3 = 3;
        p4 = -1;
        all_right = (disabled || KawigiEdit_RunTest(6, p0, p1, p2, p3, true, p4)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        if (all_right) {
            if (tests_disabled) {
                System.out.println("You're a stud (but some test cases were disabled)!");
            } else {
                System.out.println("You're a stud (at least on given cases)!");
            }
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // END KAWIGIEDIT TESTING
}

//Powered by KawigiEdit-pf 2.3.0!
