package pastchallenges;

import java.util.Arrays;

public class Target {
	public String[] draw(int n) {
		int x1 = 0, y1 = 0, x2 = n - 1, y2 = n - 1;
		char[][] ch = new char[n][n];
		for (int i = 0; i < ch.length; i++) 
			Arrays.fill(ch[i], ' ');
		
		while (x1 <= x2 && y1 <= y2) {
			for (int i = x1; i <= x2; i++) {
				ch[x1][i] = '#';
			}
			for (int i = x1; i <= x2; i++) {
				ch[x2][i] = '#';
			}
			for (int i = y1; i <= y2; i++) {
				ch[i][y1] = '#';
			}
			for (int i = y1; i <= y2; i++) {
				ch[i][y2] = '#';
			}
			x1 = x1 + 2; y1 = y1 + 2;
			x2 = x2 - 2; y2 = y2 - 2;
		}		
		String[] ans = new String[n];
		int index = 0;
		for (char[] arr : ch) {
			ans[index++] = new String(arr);
		}
		return ans;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, int p0, boolean hasAnswer, String[] p1) {
		System.out.print("Test " + testNum + ": [" + p0);
		System.out.println("]");
		Target obj;
		String[] answer;
		obj = new Target();
		long startTime = System.currentTimeMillis();
		answer = obj.draw(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p1.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print("\"" + p1[i] + "\"");
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + answer[i] + "\"");
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p1.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (!answer[i].equals(p1[i])) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;

		int p0;
		String[] p1;

		// ----- test 0 -----
		disabled = false;
		p0 = 5;
		p1 = new String[] { "#####", "#   #", "# # #", "#   #", "#####" };
		all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 1 -----
		disabled = false;
		p0 = 9;
		p1 = new String[] { "#########", "#       #", "# ##### #", "# #   # #", "# # # # #", "# #   # #", "# ##### #",
				"#       #", "#########" };
		all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 2 -----
		disabled = false;
		p0 = 13;
		p1 = new String[] { "#############", "#           #", "# ######### #", "# #       # #", "# # ##### # #",
				"# # #   # # #", "# # # # # # #", "# # #   # # #", "# # ##### # #", "# #       # #", "# ######### #",
				"#           #", "#############" };
		all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 3 -----
		disabled = false;
		p0 = 17;
		p1 = new String[] { "#################", "#               #", "# ############# #", "# #           # #",
				"# # ######### # #", "# # #       # # #", "# # # ##### # # #", "# # # #   # # # #",
				"# # # # # # # # #", "# # # #   # # # #", "# # # ##### # # #", "# # #       # # #",
				"# # ######### # #", "# #           # #", "# ############# #", "#               #", "#################" };
		all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}

// Powered by KawigiEdit-pf 2.3.0!
