import java.util.Arrays;

public class LostCharacter {
	
	private int getMyBestRank(String[] str, int i) {
		String[] arr = new String[str.length];
		int ans = 0;
		
		String temp = "";
		for (int k = 0; k < str.length; k++) {
			if (k == i) {
				temp = str[i].replaceAll("\\?", "a");
				arr[k] = temp;
			} else {
				arr[k] = str[k].replaceAll("\\?", "z");
			}
		}
		Arrays.sort(arr);
		for (int k = 0; k < arr.length; k++) {
			if (arr[k].equals(temp)) {
				ans = k;
				break;
			}
		}
		return ans;
	}
	
	public int[] getmins(String[] str) {
		int[] ans = new int[str.length];
		for (int i = 0; i < str.length; i++) {
			ans[i] = getMyBestRank(str, i);
		}
		return ans;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, int[] p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		LostCharacter obj;
		int[] answer;
		obj = new LostCharacter();
		long startTime = System.currentTimeMillis();
		answer = obj.getmins(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p1.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print(p1[i]);
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(answer[i]);
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p1.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (answer[i] != p1[i]) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;

		String[] p0;
		int[] p1;

		// ----- test 0 -----
		disabled = false;
		p0 = new String[] { "abc", "bcd", "cde", "cdf", "bbc" };
		p1 = new int[] { 0, 2, 3, 4, 1 };
		all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 1 -----
		disabled = false;
		p0 = new String[] { "?ala", "ara", "baba" };
		p1 = new int[] { 0, 0, 1 };
		all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 2 -----
		disabled = false;
		p0 = new String[] { "a?", "a", "a", "ab", "aa" };
		p1 = new int[] { 2, 0, 0, 3, 2 };
		all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 3 -----
		disabled = false;
		p0 = new String[] { "s?nu?ke", "sm??eke", "?sna?ke", "so?th?e", "shake??" };
		p1 = new int[] { 0, 1, 0, 2, 0 };
		all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 4 -----
		disabled = false;
		p0 = new String[] { "?", "z?", "zz?", "zzz?", "zzzz?", "zzzzz?", "zzzzzz?" };
		p1 = new int[] { 0, 1, 2, 3, 4, 5, 6 };
		all_right = (disabled || KawigiEdit_RunTest(4, p0, true, p1)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}

// Powered by KawigiEdit-pf 2.3.0!
