
public class TallShoes {
	public int maxHeight(int N, int[] X, int[] Y, int[] height, long B) {
		return 0;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit-pf 2.3.0
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int[] p1, int[] p2, int[] p3, long p4, boolean hasAnswer, int p5) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p2.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p2[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p3.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p3[i]);
		}
		System.out.print("}" + "," + p4);
		System.out.println("]");
		TallShoes obj;
		int answer;
		obj = new TallShoes();
		long startTime = System.currentTimeMillis();
		answer = obj.maxHeight(p0, p1, p2, p3, p4);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p5);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p5;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		boolean disabled;
		boolean tests_disabled;
		all_right = true;
		tests_disabled = false;

		int p0;
		int[] p1;
		int[] p2;
		int[] p3;
		long p4;
		int p5;

		// ----- test 0 -----
		disabled = false;
		p0 = 3;
		p1 = new int[] { 0, 1, 0 };
		p2 = new int[] { 1, 2, 2 };
		p3 = new int[] { 3, 4, 2 };
		p4 = 1L;
		p5 = 4;
		all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, p2, p3, p4, true, p5)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 1 -----
		disabled = false;
		p0 = 3;
		p1 = new int[] { 0, 1, 0 };
		p2 = new int[] { 1, 2, 2 };
		p3 = new int[] { 3, 4, 2 };
		p4 = 52L;
		p5 = 9;
		all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, p2, p3, p4, true, p5)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 2 -----
		disabled = false;
		p0 = 8;
		p1 = new int[] { 0, 0, 3, 3, 4, 4, 4, 7, 7 };
		p2 = new int[] { 1, 2, 1, 2, 3, 5, 6, 5, 6 };
		p3 = new int[] { 1000, 1000, 1000, 1000, 1, 1000, 1000, 1000, 1000 };
		p4 = 3L;
		p5 = 2;
		all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, p2, p3, p4, true, p5)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 3 -----
		disabled = false;
		p0 = 10;
		p1 = new int[] { 0, 1, 2, 3, 4, 5, 6, 7, 8 };
		p2 = new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
		p3 = new int[] { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
		p4 = 9876543210123L;
		p5 = 1047565;
		all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, p2, p3, p4, true, p5)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		// ----- test 4 -----
		disabled = false;
		p0 = 6;
		p1 = new int[] { 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4 };
		p2 = new int[] { 1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5, 4, 5, 5 };
		p3 = new int[] { 999999, 986588, 976757, 988569, 977678, 999999, 967675, 947856, 955856, 999999, 975956, 956687, 999999, 979687,
				999999 };
		p4 = 0L;
		p5 = 999999;
		all_right = (disabled || KawigiEdit_RunTest(4, p0, p1, p2, p3, p4, true, p5)) && all_right;
		tests_disabled = tests_disabled || disabled;
		// ------------------

		if (all_right) {
			if (tests_disabled) {
				System.out.println("You're a stud (but some test cases were disabled)!");
			} else {
				System.out.println("You're a stud (at least on given cases)!");
			}
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}

// Powered by KawigiEdit-pf 2.3.0!
