public class XorBoardDivTwo {
    public int theMax(String[] board) {
        int ans = 0;
        for (int row = 0; row < board.length; row++) {
            for (int col = 0; col < board[0].length(); col++) {
                char[][] ch = new char[board.length][board[0].length()];
                for (int i = 0; i < ch.length; i++) ch[i] = board[i].toCharArray();
                flipRow(ch, row);
                flipCol(ch, col);
                int cnt = countOne(ch);
                ans = Math.max(ans, cnt);
            }
        }
        return ans;
    }

    private void flipRow(char[][] ch, int row) {
        for (int i = 0; i < ch[0].length; i++) {
            ch[row][i] = ch[row][i] == '0' ? '1' : '0';
        }
    }
    private void flipCol(char[][] ch, int col) {
        for (int i = 0; i < ch.length; i++) {
            ch[i][col] = ch[i][col] == '0' ? '1' : '0';
        }
    }
    private int countOne(char[][] ch) {
        int ans = 0;
        for (char[] charArr : ch) {
            for (char item : charArr) {
                ans = item == '1' ? ans + 1 : ans;
            }
        }
        return ans++;
    }

    // BEGIN KAWIGIEDIT TESTING
    // Generated by KawigiEdit-pf 2.3.0
    private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, int p1) {
        System.out.print("Test " + testNum + ": [" + "{");
        for (int i = 0; p0.length > i; ++i) {
            if (i > 0) {
                System.out.print(",");
            }
            System.out.print("\"" + p0[i] + "\"");
        }
        System.out.print("}");
        System.out.println("]");
        XorBoardDivTwo obj;
        int answer;
        obj = new XorBoardDivTwo();
        long startTime = System.currentTimeMillis();
        answer = obj.theMax(p0);
        long endTime = System.currentTimeMillis();
        boolean res;
        res = true;
        System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
        if (hasAnswer) {
            System.out.println("Desired answer:");
            System.out.println("\t" + p1);
        }
        System.out.println("Your answer:");
        System.out.println("\t" + answer);
        if (hasAnswer) {
            res = answer == p1;
        }
        if (!res) {
            System.out.println("DOESN'T MATCH!!!!");
        } else if ((endTime - startTime) / 1000.0 >= 2) {
            System.out.println("FAIL the timeout");
            res = false;
        } else if (hasAnswer) {
            System.out.println("Match :-)");
        } else {
            System.out.println("OK, but is it right?");
        }
        System.out.println("");
        return res;
    }

    public static void main(String[] args) {
        boolean all_right;
        boolean disabled;
        boolean tests_disabled;
        all_right = true;
        tests_disabled = false;

        String[] p0;
        int p1;

        // ----- test 0 -----
        disabled = false;
        p0 = new String[]{"101", "010", "101"};
        p1 = 9;
        all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        // ----- test 1 -----
        disabled = false;
        p0 = new String[]{"111", "111", "111"};
        p1 = 5;
        all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        // ----- test 2 -----
        disabled = false;
        p0 = new String[]{"0101001", "1101011"};
        p1 = 9;
        all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        // ----- test 3 -----
        disabled = false;
        p0 = new String[]{"000", "001", "010", "011", "100", "101", "110", "111"};
        p1 = 15;
        all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        // ----- test 4 -----
        disabled = false;
        p0 = new String[]{"000000000000000000000000", "011111100111111001111110", "010000000100000001000000", "010000000100000001000000", "010000000100000001000000", "011111100111111001111110", "000000100000001000000010", "000000100000001000000010", "000000100000001000000010", "011111100111111001111110", "000000000000000000000000"};
        p1 = 105;
        all_right = (disabled || KawigiEdit_RunTest(4, p0, true, p1)) && all_right;
        tests_disabled = tests_disabled || disabled;
        // ------------------

        if (all_right) {
            if (tests_disabled) {
                System.out.println("You're a stud (but some test cases were disabled)!");
            } else {
                System.out.println("You're a stud (at least on given cases)!");
            }
        } else {
            System.out.println("Some of the test cases had errors.");
        }
    }
    // END KAWIGIEDIT TESTING
}

//Powered by KawigiEdit-pf 2.3.0!
